name: Package Release

on:
  release:
    types: [created]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          [
            'chrome',
            'firefox',
          ]
    env:
      BROWSER: ${{ matrix.container }}
      VERSION: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - name: build Chrome
      if: ${{ matrix.container == 'chrome' }}
      run: npm run build
    - name: build Firefox 
      if: ${{ matrix.container == 'firefox' }}
      run: |
        sed -i 's,"service_worker": "dist/background.js","scripts": ["dist/background.js"],g' ./manifest.json
        npm run build
    - name: package
      run: |
        PACKAGE_NAME="BandcampEnhancementSuite_${BROWSER}-$VERSION.zip"
        zip $PACKAGE_NAME LICENSE _locales/**/* icons/* css/* dist/* manifest.json html/browser_action.html
    - name: attach packages to GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GH_RELEASE_ID=${{ github.event.release.id }}
        GH_REPO="https://uploads.github.com/repos/${{ github.repository }}/releases/$GH_RELEASE_ID/assets"
        PACKAGE_NAME="BandcampEnhancementSuite_${BROWSER}-$VERSION.zip"
        
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/octet-stream" \
          "$GH_REPO?name=$PACKAGE_NAME" \
          --data-binary "@$PACKAGE_NAME"
