name: Package Release

on:
  release:
    types: [created]

jobs:
  build-and-package:
    runs-on: macos-latest
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run package
    - name: attach packages to GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GH_RELEASE_ID=${{ github.event.release.id }}
        GH_REPO="https://uploads.github.com/repos/${{ github.repository }}/releases/$GH_RELEASE_ID/assets"
        BROWSERS=("chrome" "firefox")

        for BROWSER in "${BROWSERS[@]}"; do
            PACKAGE_NAME="BandcampEnhancementSuite_${BROWSER}-$VERSION.zip"
            mv "BandcampEnhancementSuite_${BROWSER}.zip" "$PACKAGE_NAME"
            
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Content-Type: application/octet-stream" \
              "$GH_REPO?name=$PACKAGE_NAME" \
              --data-binary "@$PACKAGE_NAME"
        done
